// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgozxfzqafduesaovyjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nb3p4ZnpxYWZkdWVzYW92eWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODI1NTYsImV4cCI6MjA3NDM1ODU1Nn0.USmAJJCKzjzAC4AgwfKg2DYdxzeqJXEx0mibRi4EebQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});